// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.3
// source: extension.proto

package wire

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExtensionPlugin_GetInfo_FullMethodName        = "/sub2api.plugin.v2.ExtensionPlugin/GetInfo"
	ExtensionPlugin_Health_FullMethodName         = "/sub2api.plugin.v2.ExtensionPlugin/Health"
	ExtensionPlugin_ValidateConfig_FullMethodName = "/sub2api.plugin.v2.ExtensionPlugin/ValidateConfig"
	ExtensionPlugin_ApplyConfig_FullMethodName    = "/sub2api.plugin.v2.ExtensionPlugin/ApplyConfig"
	ExtensionPlugin_TestConfig_FullMethodName     = "/sub2api.plugin.v2.ExtensionPlugin/TestConfig"
	ExtensionPlugin_Preprocess_FullMethodName     = "/sub2api.plugin.v2.ExtensionPlugin/Preprocess"
	ExtensionPlugin_AttachHost_FullMethodName     = "/sub2api.plugin.v2.ExtensionPlugin/AttachHost"
)

// ExtensionPluginClient is the client API for ExtensionPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ExtensionPlugin is the generic user-space extension contract. The existing
// v1 TransportPlugin remains available for backwards compatibility.
type ExtensionPluginClient interface {
	GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	ValidateConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error)
	ApplyConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ApplyResponse, error)
	TestConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*TestResponse, error)
	Preprocess(ctx context.Context, in *PreprocessRequest, opts ...grpc.CallOption) (*PreprocessResponse, error)
	AttachHost(ctx context.Context, in *AttachHostRequest, opts ...grpc.CallOption) (*ApplyResponse, error)
}

type extensionPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewExtensionPluginClient(cc grpc.ClientConnInterface) ExtensionPluginClient {
	return &extensionPluginClient{cc}
}

func (c *extensionPluginClient) GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInfoResponse)
	err := c.cc.Invoke(ctx, ExtensionPlugin_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionPluginClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, ExtensionPlugin_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionPluginClient) ValidateConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigResponse)
	err := c.cc.Invoke(ctx, ExtensionPlugin_ValidateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionPluginClient) ApplyConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ApplyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyResponse)
	err := c.cc.Invoke(ctx, ExtensionPlugin_ApplyConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionPluginClient) TestConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*TestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestResponse)
	err := c.cc.Invoke(ctx, ExtensionPlugin_TestConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionPluginClient) Preprocess(ctx context.Context, in *PreprocessRequest, opts ...grpc.CallOption) (*PreprocessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreprocessResponse)
	err := c.cc.Invoke(ctx, ExtensionPlugin_Preprocess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionPluginClient) AttachHost(ctx context.Context, in *AttachHostRequest, opts ...grpc.CallOption) (*ApplyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyResponse)
	err := c.cc.Invoke(ctx, ExtensionPlugin_AttachHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExtensionPluginServer is the server API for ExtensionPlugin service.
// All implementations must embed UnimplementedExtensionPluginServer
// for forward compatibility.
//
// ExtensionPlugin is the generic user-space extension contract. The existing
// v1 TransportPlugin remains available for backwards compatibility.
type ExtensionPluginServer interface {
	GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	ValidateConfig(context.Context, *ConfigRequest) (*ConfigResponse, error)
	ApplyConfig(context.Context, *ConfigRequest) (*ApplyResponse, error)
	TestConfig(context.Context, *ConfigRequest) (*TestResponse, error)
	Preprocess(context.Context, *PreprocessRequest) (*PreprocessResponse, error)
	AttachHost(context.Context, *AttachHostRequest) (*ApplyResponse, error)
	mustEmbedUnimplementedExtensionPluginServer()
}

// UnimplementedExtensionPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExtensionPluginServer struct{}

func (UnimplementedExtensionPluginServer) GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedExtensionPluginServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedExtensionPluginServer) ValidateConfig(context.Context, *ConfigRequest) (*ConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateConfig not implemented")
}
func (UnimplementedExtensionPluginServer) ApplyConfig(context.Context, *ConfigRequest) (*ApplyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyConfig not implemented")
}
func (UnimplementedExtensionPluginServer) TestConfig(context.Context, *ConfigRequest) (*TestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TestConfig not implemented")
}
func (UnimplementedExtensionPluginServer) Preprocess(context.Context, *PreprocessRequest) (*PreprocessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Preprocess not implemented")
}
func (UnimplementedExtensionPluginServer) AttachHost(context.Context, *AttachHostRequest) (*ApplyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AttachHost not implemented")
}
func (UnimplementedExtensionPluginServer) mustEmbedUnimplementedExtensionPluginServer() {}
func (UnimplementedExtensionPluginServer) testEmbeddedByValue()                         {}

// UnsafeExtensionPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExtensionPluginServer will
// result in compilation errors.
type UnsafeExtensionPluginServer interface {
	mustEmbedUnimplementedExtensionPluginServer()
}

func RegisterExtensionPluginServer(s grpc.ServiceRegistrar, srv ExtensionPluginServer) {
	// If the following call panics, it indicates UnimplementedExtensionPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExtensionPlugin_ServiceDesc, srv)
}

func _ExtensionPlugin_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionPluginServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtensionPlugin_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionPluginServer).GetInfo(ctx, req.(*GetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtensionPlugin_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionPluginServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtensionPlugin_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionPluginServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtensionPlugin_ValidateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionPluginServer).ValidateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtensionPlugin_ValidateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionPluginServer).ValidateConfig(ctx, req.(*ConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtensionPlugin_ApplyConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionPluginServer).ApplyConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtensionPlugin_ApplyConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionPluginServer).ApplyConfig(ctx, req.(*ConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtensionPlugin_TestConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionPluginServer).TestConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtensionPlugin_TestConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionPluginServer).TestConfig(ctx, req.(*ConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtensionPlugin_Preprocess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreprocessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionPluginServer).Preprocess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtensionPlugin_Preprocess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionPluginServer).Preprocess(ctx, req.(*PreprocessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtensionPlugin_AttachHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionPluginServer).AttachHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtensionPlugin_AttachHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionPluginServer).AttachHost(ctx, req.(*AttachHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExtensionPlugin_ServiceDesc is the grpc.ServiceDesc for ExtensionPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExtensionPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sub2api.plugin.v2.ExtensionPlugin",
	HandlerType: (*ExtensionPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _ExtensionPlugin_GetInfo_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _ExtensionPlugin_Health_Handler,
		},
		{
			MethodName: "ValidateConfig",
			Handler:    _ExtensionPlugin_ValidateConfig_Handler,
		},
		{
			MethodName: "ApplyConfig",
			Handler:    _ExtensionPlugin_ApplyConfig_Handler,
		},
		{
			MethodName: "TestConfig",
			Handler:    _ExtensionPlugin_TestConfig_Handler,
		},
		{
			MethodName: "Preprocess",
			Handler:    _ExtensionPlugin_Preprocess_Handler,
		},
		{
			MethodName: "AttachHost",
			Handler:    _ExtensionPlugin_AttachHost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "extension.proto",
}

const (
	HostServices_Log_FullMethodName          = "/sub2api.plugin.v2.HostServices/Log"
	HostServices_Metric_FullMethodName       = "/sub2api.plugin.v2.HostServices/Metric"
	HostServices_ReadConfig_FullMethodName   = "/sub2api.plugin.v2.HostServices/ReadConfig"
	HostServices_ReadSecret_FullMethodName   = "/sub2api.plugin.v2.HostServices/ReadSecret"
	HostServices_PublishEvent_FullMethodName = "/sub2api.plugin.v2.HostServices/PublishEvent"
)

// HostServicesClient is the client API for HostServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Each HostServices server is bound by the host to one verified installation.
// No operation accepts an installation ID, environment key, or database query.
type HostServicesClient interface {
	Log(ctx context.Context, in *HostLogRequest, opts ...grpc.CallOption) (*HostAck, error)
	Metric(ctx context.Context, in *HostMetricRequest, opts ...grpc.CallOption) (*HostAck, error)
	ReadConfig(ctx context.Context, in *HostCapabilityRequest, opts ...grpc.CallOption) (*HostConfigResponse, error)
	ReadSecret(ctx context.Context, in *HostSecretRequest, opts ...grpc.CallOption) (*HostSecretResponse, error)
	PublishEvent(ctx context.Context, in *HostEventRequest, opts ...grpc.CallOption) (*HostAck, error)
}

type hostServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewHostServicesClient(cc grpc.ClientConnInterface) HostServicesClient {
	return &hostServicesClient{cc}
}

func (c *hostServicesClient) Log(ctx context.Context, in *HostLogRequest, opts ...grpc.CallOption) (*HostAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostAck)
	err := c.cc.Invoke(ctx, HostServices_Log_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) Metric(ctx context.Context, in *HostMetricRequest, opts ...grpc.CallOption) (*HostAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostAck)
	err := c.cc.Invoke(ctx, HostServices_Metric_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) ReadConfig(ctx context.Context, in *HostCapabilityRequest, opts ...grpc.CallOption) (*HostConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostConfigResponse)
	err := c.cc.Invoke(ctx, HostServices_ReadConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) ReadSecret(ctx context.Context, in *HostSecretRequest, opts ...grpc.CallOption) (*HostSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostSecretResponse)
	err := c.cc.Invoke(ctx, HostServices_ReadSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) PublishEvent(ctx context.Context, in *HostEventRequest, opts ...grpc.CallOption) (*HostAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostAck)
	err := c.cc.Invoke(ctx, HostServices_PublishEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostServicesServer is the server API for HostServices service.
// All implementations must embed UnimplementedHostServicesServer
// for forward compatibility.
//
// Each HostServices server is bound by the host to one verified installation.
// No operation accepts an installation ID, environment key, or database query.
type HostServicesServer interface {
	Log(context.Context, *HostLogRequest) (*HostAck, error)
	Metric(context.Context, *HostMetricRequest) (*HostAck, error)
	ReadConfig(context.Context, *HostCapabilityRequest) (*HostConfigResponse, error)
	ReadSecret(context.Context, *HostSecretRequest) (*HostSecretResponse, error)
	PublishEvent(context.Context, *HostEventRequest) (*HostAck, error)
	mustEmbedUnimplementedHostServicesServer()
}

// UnimplementedHostServicesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostServicesServer struct{}

func (UnimplementedHostServicesServer) Log(context.Context, *HostLogRequest) (*HostAck, error) {
	return nil, status.Error(codes.Unimplemented, "method Log not implemented")
}
func (UnimplementedHostServicesServer) Metric(context.Context, *HostMetricRequest) (*HostAck, error) {
	return nil, status.Error(codes.Unimplemented, "method Metric not implemented")
}
func (UnimplementedHostServicesServer) ReadConfig(context.Context, *HostCapabilityRequest) (*HostConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadConfig not implemented")
}
func (UnimplementedHostServicesServer) ReadSecret(context.Context, *HostSecretRequest) (*HostSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadSecret not implemented")
}
func (UnimplementedHostServicesServer) PublishEvent(context.Context, *HostEventRequest) (*HostAck, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishEvent not implemented")
}
func (UnimplementedHostServicesServer) mustEmbedUnimplementedHostServicesServer() {}
func (UnimplementedHostServicesServer) testEmbeddedByValue()                      {}

// UnsafeHostServicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostServicesServer will
// result in compilation errors.
type UnsafeHostServicesServer interface {
	mustEmbedUnimplementedHostServicesServer()
}

func RegisterHostServicesServer(s grpc.ServiceRegistrar, srv HostServicesServer) {
	// If the following call panics, it indicates UnimplementedHostServicesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HostServices_ServiceDesc, srv)
}

func _HostServices_Log_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).Log(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_Log_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).Log(ctx, req.(*HostLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_Metric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostMetricRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).Metric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_Metric_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).Metric(ctx, req.(*HostMetricRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_ReadConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostCapabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).ReadConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_ReadConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).ReadConfig(ctx, req.(*HostCapabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_ReadSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).ReadSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_ReadSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).ReadSecret(ctx, req.(*HostSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_PublishEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).PublishEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_PublishEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).PublishEvent(ctx, req.(*HostEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HostServices_ServiceDesc is the grpc.ServiceDesc for HostServices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostServices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sub2api.plugin.v2.HostServices",
	HandlerType: (*HostServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Log",
			Handler:    _HostServices_Log_Handler,
		},
		{
			MethodName: "Metric",
			Handler:    _HostServices_Metric_Handler,
		},
		{
			MethodName: "ReadConfig",
			Handler:    _HostServices_ReadConfig_Handler,
		},
		{
			MethodName: "ReadSecret",
			Handler:    _HostServices_ReadSecret_Handler,
		},
		{
			MethodName: "PublishEvent",
			Handler:    _HostServices_PublishEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "extension.proto",
}
