// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: extension.proto

package wire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AttachHostRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BrokerId       uint32                 `protobuf:"varint,1,opt,name=broker_id,json=brokerId,proto3" json:"broker_id,omitempty"`
	HostApiVersion uint32                 `protobuf:"varint,2,opt,name=host_api_version,json=hostApiVersion,proto3" json:"host_api_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AttachHostRequest) Reset() {
	*x = AttachHostRequest{}
	mi := &file_extension_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachHostRequest) ProtoMessage() {}

func (x *AttachHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachHostRequest.ProtoReflect.Descriptor instead.
func (*AttachHostRequest) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{0}
}

func (x *AttachHostRequest) GetBrokerId() uint32 {
	if x != nil {
		return x.BrokerId
	}
	return 0
}

func (x *AttachHostRequest) GetHostApiVersion() uint32 {
	if x != nil {
		return x.HostApiVersion
	}
	return 0
}

type HostCapabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capability    string                 `protobuf:"bytes,1,opt,name=capability,proto3" json:"capability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostCapabilityRequest) Reset() {
	*x = HostCapabilityRequest{}
	mi := &file_extension_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostCapabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostCapabilityRequest) ProtoMessage() {}

func (x *HostCapabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostCapabilityRequest.ProtoReflect.Descriptor instead.
func (*HostCapabilityRequest) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{1}
}

func (x *HostCapabilityRequest) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

type HostLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capability    string                 `protobuf:"bytes,1,opt,name=capability,proto3" json:"capability,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostLogRequest) Reset() {
	*x = HostLogRequest{}
	mi := &file_extension_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostLogRequest) ProtoMessage() {}

func (x *HostLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostLogRequest.ProtoReflect.Descriptor instead.
func (*HostLogRequest) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{2}
}

func (x *HostLogRequest) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *HostLogRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *HostLogRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type HostMetricRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capability    string                 `protobuf:"bytes,1,opt,name=capability,proto3" json:"capability,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostMetricRequest) Reset() {
	*x = HostMetricRequest{}
	mi := &file_extension_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostMetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostMetricRequest) ProtoMessage() {}

func (x *HostMetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostMetricRequest.ProtoReflect.Descriptor instead.
func (*HostMetricRequest) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{3}
}

func (x *HostMetricRequest) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *HostMetricRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HostMetricRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type HostConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigJson    []byte                 `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostConfigResponse) Reset() {
	*x = HostConfigResponse{}
	mi := &file_extension_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostConfigResponse) ProtoMessage() {}

func (x *HostConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostConfigResponse.ProtoReflect.Descriptor instead.
func (*HostConfigResponse) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{4}
}

func (x *HostConfigResponse) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

type HostSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capability    string                 `protobuf:"bytes,1,opt,name=capability,proto3" json:"capability,omitempty"`
	Alias         string                 `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostSecretRequest) Reset() {
	*x = HostSecretRequest{}
	mi := &file_extension_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostSecretRequest) ProtoMessage() {}

func (x *HostSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostSecretRequest.ProtoReflect.Descriptor instead.
func (*HostSecretRequest) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{5}
}

func (x *HostSecretRequest) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *HostSecretRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type HostSecretResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Value             []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	ExpiresUnixMillis int64                  `protobuf:"varint,2,opt,name=expires_unix_millis,json=expiresUnixMillis,proto3" json:"expires_unix_millis,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HostSecretResponse) Reset() {
	*x = HostSecretResponse{}
	mi := &file_extension_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostSecretResponse) ProtoMessage() {}

func (x *HostSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostSecretResponse.ProtoReflect.Descriptor instead.
func (*HostSecretResponse) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{6}
}

func (x *HostSecretResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *HostSecretResponse) GetExpiresUnixMillis() int64 {
	if x != nil {
		return x.ExpiresUnixMillis
	}
	return 0
}

type HostEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capability    string                 `protobuf:"bytes,1,opt,name=capability,proto3" json:"capability,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value         int64                  `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostEventRequest) Reset() {
	*x = HostEventRequest{}
	mi := &file_extension_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostEventRequest) ProtoMessage() {}

func (x *HostEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostEventRequest.ProtoReflect.Descriptor instead.
func (*HostEventRequest) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{7}
}

func (x *HostEventRequest) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *HostEventRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HostEventRequest) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type HostAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostAck) Reset() {
	*x = HostAck{}
	mi := &file_extension_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostAck) ProtoMessage() {}

func (x *HostAck) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostAck.ProtoReflect.Descriptor instead.
func (*HostAck) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{8}
}

func (x *HostAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_extension_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{9}
}

type GetInfoResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PluginId        string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	PluginVersion   string                 `protobuf:"bytes,2,opt,name=plugin_version,json=pluginVersion,proto3" json:"plugin_version,omitempty"`
	ProtocolVersion uint32                 `protobuf:"varint,3,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Capabilities    []*Capability          `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetInfoResponse) Reset() {
	*x = GetInfoResponse{}
	mi := &file_extension_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResponse) ProtoMessage() {}

func (x *GetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{10}
}

func (x *GetInfoResponse) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *GetInfoResponse) GetPluginVersion() string {
	if x != nil {
		return x.PluginVersion
	}
	return ""
}

func (x *GetInfoResponse) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *GetInfoResponse) GetCapabilities() []*Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type Capability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	AccountType   string                 `protobuf:"bytes,4,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	Permissions   []string               `protobuf:"bytes,5,rep,name=permissions,proto3" json:"permissions,omitempty"`
	TimeoutMs     int64                  `protobuf:"varint,6,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	FailureMode   string                 `protobuf:"bytes,7,opt,name=failure_mode,json=failureMode,proto3" json:"failure_mode,omitempty"`
	Synchronous   bool                   `protobuf:"varint,8,opt,name=synchronous,proto3" json:"synchronous,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capability) Reset() {
	*x = Capability{}
	mi := &file_extension_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capability) ProtoMessage() {}

func (x *Capability) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capability.ProtoReflect.Descriptor instead.
func (*Capability) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{11}
}

func (x *Capability) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Capability) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Capability) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *Capability) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *Capability) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *Capability) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *Capability) GetFailureMode() string {
	if x != nil {
		return x.FailureMode
	}
	return ""
}

func (x *Capability) GetSynchronous() bool {
	if x != nil {
		return x.Synchronous
	}
	return false
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_extension_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{12}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_extension_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{13}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigJson    []byte                 `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigRequest) Reset() {
	*x = ConfigRequest{}
	mi := &file_extension_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigRequest) ProtoMessage() {}

func (x *ConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigRequest.ProtoReflect.Descriptor instead.
func (*ConfigRequest) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{14}
}

func (x *ConfigRequest) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

type ConfigResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Valid                bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	NormalizedConfigJson []byte                 `protobuf:"bytes,2,opt,name=normalized_config_json,json=normalizedConfigJson,proto3" json:"normalized_config_json,omitempty"`
	Message              string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ConfigResponse) Reset() {
	*x = ConfigResponse{}
	mi := &file_extension_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigResponse) ProtoMessage() {}

func (x *ConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigResponse.ProtoReflect.Descriptor instead.
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{15}
}

func (x *ConfigResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ConfigResponse) GetNormalizedConfigJson() []byte {
	if x != nil {
		return x.NormalizedConfigJson
	}
	return nil
}

func (x *ConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applied       bool                   `protobuf:"varint,1,opt,name=applied,proto3" json:"applied,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyResponse) Reset() {
	*x = ApplyResponse{}
	mi := &file_extension_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResponse) ProtoMessage() {}

func (x *ApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResponse.ProtoReflect.Descriptor instead.
func (*ApplyResponse) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{16}
}

func (x *ApplyResponse) GetApplied() bool {
	if x != nil {
		return x.Applied
	}
	return false
}

func (x *ApplyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestResponse) Reset() {
	*x = TestResponse{}
	mi := &file_extension_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResponse) ProtoMessage() {}

func (x *TestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResponse.ProtoReflect.Descriptor instead.
func (*TestResponse) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{17}
}

func (x *TestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TestResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

type RequestContext struct {
	state              protoimpl.MessageState   `protogen:"open.v1"`
	RequestId          string                   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TraceId            string                   `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	DeadlineUnixMillis int64                    `protobuf:"varint,3,opt,name=deadline_unix_millis,json=deadlineUnixMillis,proto3" json:"deadline_unix_millis,omitempty"`
	Platform           string                   `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	AccountType        string                   `protobuf:"bytes,5,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	AccountId          int64                    `protobuf:"varint,6,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	UserId             int64                    `protobuf:"varint,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GroupId            int64                    `protobuf:"varint,8,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Method             string                   `protobuf:"bytes,9,opt,name=method,proto3" json:"method,omitempty"`
	Path               string                   `protobuf:"bytes,10,opt,name=path,proto3" json:"path,omitempty"`
	Host               string                   `protobuf:"bytes,11,opt,name=host,proto3" json:"host,omitempty"`
	Model              string                   `protobuf:"bytes,12,opt,name=model,proto3" json:"model,omitempty"`
	Headers            map[string]*HeaderValues `protobuf:"bytes,13,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RequestContext) Reset() {
	*x = RequestContext{}
	mi := &file_extension_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestContext) ProtoMessage() {}

func (x *RequestContext) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestContext.ProtoReflect.Descriptor instead.
func (*RequestContext) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{18}
}

func (x *RequestContext) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestContext) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *RequestContext) GetDeadlineUnixMillis() int64 {
	if x != nil {
		return x.DeadlineUnixMillis
	}
	return 0
}

func (x *RequestContext) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *RequestContext) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *RequestContext) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *RequestContext) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RequestContext) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *RequestContext) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RequestContext) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RequestContext) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *RequestContext) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *RequestContext) GetHeaders() map[string]*HeaderValues {
	if x != nil {
		return x.Headers
	}
	return nil
}

type HeaderValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderValues) Reset() {
	*x = HeaderValues{}
	mi := &file_extension_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderValues) ProtoMessage() {}

func (x *HeaderValues) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderValues.ProtoReflect.Descriptor instead.
func (*HeaderValues) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{19}
}

func (x *HeaderValues) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type PreprocessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capability    string                 `protobuf:"bytes,1,opt,name=capability,proto3" json:"capability,omitempty"`
	Context       *RequestContext        `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	BodyJson      []byte                 `protobuf:"bytes,3,opt,name=body_json,json=bodyJson,proto3" json:"body_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreprocessRequest) Reset() {
	*x = PreprocessRequest{}
	mi := &file_extension_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreprocessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreprocessRequest) ProtoMessage() {}

func (x *PreprocessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreprocessRequest.ProtoReflect.Descriptor instead.
func (*PreprocessRequest) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{20}
}

func (x *PreprocessRequest) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *PreprocessRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *PreprocessRequest) GetBodyJson() []byte {
	if x != nil {
		return x.BodyJson
	}
	return nil
}

type RequestPatch struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Method        string                   `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Headers       map[string]*HeaderValues `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	BodyJson      []byte                   `protobuf:"bytes,4,opt,name=body_json,json=bodyJson,proto3" json:"body_json,omitempty"`
	BodyChanged   bool                     `protobuf:"varint,5,opt,name=body_changed,json=bodyChanged,proto3" json:"body_changed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestPatch) Reset() {
	*x = RequestPatch{}
	mi := &file_extension_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPatch) ProtoMessage() {}

func (x *RequestPatch) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPatch.ProtoReflect.Descriptor instead.
func (*RequestPatch) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{21}
}

func (x *RequestPatch) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RequestPatch) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RequestPatch) GetHeaders() map[string]*HeaderValues {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *RequestPatch) GetBodyJson() []byte {
	if x != nil {
		return x.BodyJson
	}
	return nil
}

func (x *RequestPatch) GetBodyChanged() bool {
	if x != nil {
		return x.BodyChanged
	}
	return false
}

type PreprocessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decision      string                 `protobuf:"bytes,1,opt,name=decision,proto3" json:"decision,omitempty"`
	Patch         *RequestPatch          `protobuf:"bytes,2,opt,name=patch,proto3" json:"patch,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreprocessResponse) Reset() {
	*x = PreprocessResponse{}
	mi := &file_extension_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreprocessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreprocessResponse) ProtoMessage() {}

func (x *PreprocessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreprocessResponse.ProtoReflect.Descriptor instead.
func (*PreprocessResponse) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{22}
}

func (x *PreprocessResponse) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *PreprocessResponse) GetPatch() *RequestPatch {
	if x != nil {
		return x.Patch
	}
	return nil
}

func (x *PreprocessResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PreprocessResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_extension_proto protoreflect.FileDescriptor

const file_extension_proto_rawDesc = "" +
	"\n" +
	"\x0fextension.proto\x12\x11sub2api.plugin.v2\"Z\n" +
	"\x11AttachHostRequest\x12\x1b\n" +
	"\tbroker_id\x18\x01 \x01(\rR\bbrokerId\x12(\n" +
	"\x10host_api_version\x18\x02 \x01(\rR\x0ehostApiVersion\"7\n" +
	"\x15HostCapabilityRequest\x12\x1e\n" +
	"\n" +
	"capability\x18\x01 \x01(\tR\n" +
	"capability\"Z\n" +
	"\x0eHostLogRequest\x12\x1e\n" +
	"\n" +
	"capability\x18\x01 \x01(\tR\n" +
	"capability\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"]\n" +
	"\x11HostMetricRequest\x12\x1e\n" +
	"\n" +
	"capability\x18\x01 \x01(\tR\n" +
	"capability\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\"5\n" +
	"\x12HostConfigResponse\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\fR\n" +
	"configJson\"I\n" +
	"\x11HostSecretRequest\x12\x1e\n" +
	"\n" +
	"capability\x18\x01 \x01(\tR\n" +
	"capability\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\"Z\n" +
	"\x12HostSecretResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12.\n" +
	"\x13expires_unix_millis\x18\x02 \x01(\x03R\x11expiresUnixMillis\"\\\n" +
	"\x10HostEventRequest\x12\x1e\n" +
	"\n" +
	"capability\x18\x01 \x01(\tR\n" +
	"capability\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x03R\x05value\"%\n" +
	"\aHostAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"\x10\n" +
	"\x0eGetInfoRequest\"\xc3\x01\n" +
	"\x0fGetInfoResponse\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12%\n" +
	"\x0eplugin_version\x18\x02 \x01(\tR\rpluginVersion\x12)\n" +
	"\x10protocol_version\x18\x03 \x01(\rR\x0fprotocolVersion\x12A\n" +
	"\fcapabilities\x18\x04 \x03(\v2\x1d.sub2api.plugin.v2.CapabilityR\fcapabilities\"\xf5\x01\n" +
	"\n" +
	"Capability\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12!\n" +
	"\faccount_type\x18\x04 \x01(\tR\vaccountType\x12 \n" +
	"\vpermissions\x18\x05 \x03(\tR\vpermissions\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x06 \x01(\x03R\ttimeoutMs\x12!\n" +
	"\ffailure_mode\x18\a \x01(\tR\vfailureMode\x12 \n" +
	"\vsynchronous\x18\b \x01(\bR\vsynchronous\"\x0f\n" +
	"\rHealthRequest\"D\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"0\n" +
	"\rConfigRequest\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\fR\n" +
	"configJson\"v\n" +
	"\x0eConfigResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x124\n" +
	"\x16normalized_config_json\x18\x02 \x01(\fR\x14normalizedConfigJson\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"C\n" +
	"\rApplyResponse\x12\x18\n" +
	"\aapplied\x18\x01 \x01(\bR\aapplied\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"a\n" +
	"\fTestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x03 \x01(\x03R\tlatencyMs\"\x8b\x04\n" +
	"\x0eRequestContext\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x120\n" +
	"\x14deadline_unix_millis\x18\x03 \x01(\x03R\x12deadlineUnixMillis\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12!\n" +
	"\faccount_type\x18\x05 \x01(\tR\vaccountType\x12\x1d\n" +
	"\n" +
	"account_id\x18\x06 \x01(\x03R\taccountId\x12\x17\n" +
	"\auser_id\x18\a \x01(\x03R\x06userId\x12\x19\n" +
	"\bgroup_id\x18\b \x01(\x03R\agroupId\x12\x16\n" +
	"\x06method\x18\t \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\n" +
	" \x01(\tR\x04path\x12\x12\n" +
	"\x04host\x18\v \x01(\tR\x04host\x12\x14\n" +
	"\x05model\x18\f \x01(\tR\x05model\x12H\n" +
	"\aheaders\x18\r \x03(\v2..sub2api.plugin.v2.RequestContext.HeadersEntryR\aheaders\x1a[\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.sub2api.plugin.v2.HeaderValuesR\x05value:\x028\x01\"&\n" +
	"\fHeaderValues\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\x8d\x01\n" +
	"\x11PreprocessRequest\x12\x1e\n" +
	"\n" +
	"capability\x18\x01 \x01(\tR\n" +
	"capability\x12;\n" +
	"\acontext\x18\x02 \x01(\v2!.sub2api.plugin.v2.RequestContextR\acontext\x12\x1b\n" +
	"\tbody_json\x18\x03 \x01(\fR\bbodyJson\"\x9f\x02\n" +
	"\fRequestPatch\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12F\n" +
	"\aheaders\x18\x03 \x03(\v2,.sub2api.plugin.v2.RequestPatch.HeadersEntryR\aheaders\x12\x1b\n" +
	"\tbody_json\x18\x04 \x01(\fR\bbodyJson\x12!\n" +
	"\fbody_changed\x18\x05 \x01(\bR\vbodyChanged\x1a[\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.sub2api.plugin.v2.HeaderValuesR\x05value:\x028\x01\"\x93\x01\n" +
	"\x12PreprocessResponse\x12\x1a\n" +
	"\bdecision\x18\x01 \x01(\tR\bdecision\x125\n" +
	"\x05patch\x18\x02 \x01(\v2\x1f.sub2api.plugin.v2.RequestPatchR\x05patch\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason2\xde\x04\n" +
	"\x0fExtensionPlugin\x12P\n" +
	"\aGetInfo\x12!.sub2api.plugin.v2.GetInfoRequest\x1a\".sub2api.plugin.v2.GetInfoResponse\x12M\n" +
	"\x06Health\x12 .sub2api.plugin.v2.HealthRequest\x1a!.sub2api.plugin.v2.HealthResponse\x12U\n" +
	"\x0eValidateConfig\x12 .sub2api.plugin.v2.ConfigRequest\x1a!.sub2api.plugin.v2.ConfigResponse\x12Q\n" +
	"\vApplyConfig\x12 .sub2api.plugin.v2.ConfigRequest\x1a .sub2api.plugin.v2.ApplyResponse\x12O\n" +
	"\n" +
	"TestConfig\x12 .sub2api.plugin.v2.ConfigRequest\x1a\x1f.sub2api.plugin.v2.TestResponse\x12Y\n" +
	"\n" +
	"Preprocess\x12$.sub2api.plugin.v2.PreprocessRequest\x1a%.sub2api.plugin.v2.PreprocessResponse\x12T\n" +
	"\n" +
	"AttachHost\x12$.sub2api.plugin.v2.AttachHostRequest\x1a .sub2api.plugin.v2.ApplyResponse2\xab\x03\n" +
	"\fHostServices\x12D\n" +
	"\x03Log\x12!.sub2api.plugin.v2.HostLogRequest\x1a\x1a.sub2api.plugin.v2.HostAck\x12J\n" +
	"\x06Metric\x12$.sub2api.plugin.v2.HostMetricRequest\x1a\x1a.sub2api.plugin.v2.HostAck\x12]\n" +
	"\n" +
	"ReadConfig\x12(.sub2api.plugin.v2.HostCapabilityRequest\x1a%.sub2api.plugin.v2.HostConfigResponse\x12Y\n" +
	"\n" +
	"ReadSecret\x12$.sub2api.plugin.v2.HostSecretRequest\x1a%.sub2api.plugin.v2.HostSecretResponse\x12O\n" +
	"\fPublishEvent\x12#.sub2api.plugin.v2.HostEventRequest\x1a\x1a.sub2api.plugin.v2.HostAckB8Z6github.com/Wei-Shaw/sub2api/pkg/pluginapi/v2/wire;wireb\x06proto3"

var (
	file_extension_proto_rawDescOnce sync.Once
	file_extension_proto_rawDescData []byte
)

func file_extension_proto_rawDescGZIP() []byte {
	file_extension_proto_rawDescOnce.Do(func() {
		file_extension_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_extension_proto_rawDesc), len(file_extension_proto_rawDesc)))
	})
	return file_extension_proto_rawDescData
}

var file_extension_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_extension_proto_goTypes = []any{
	(*AttachHostRequest)(nil),     // 0: sub2api.plugin.v2.AttachHostRequest
	(*HostCapabilityRequest)(nil), // 1: sub2api.plugin.v2.HostCapabilityRequest
	(*HostLogRequest)(nil),        // 2: sub2api.plugin.v2.HostLogRequest
	(*HostMetricRequest)(nil),     // 3: sub2api.plugin.v2.HostMetricRequest
	(*HostConfigResponse)(nil),    // 4: sub2api.plugin.v2.HostConfigResponse
	(*HostSecretRequest)(nil),     // 5: sub2api.plugin.v2.HostSecretRequest
	(*HostSecretResponse)(nil),    // 6: sub2api.plugin.v2.HostSecretResponse
	(*HostEventRequest)(nil),      // 7: sub2api.plugin.v2.HostEventRequest
	(*HostAck)(nil),               // 8: sub2api.plugin.v2.HostAck
	(*GetInfoRequest)(nil),        // 9: sub2api.plugin.v2.GetInfoRequest
	(*GetInfoResponse)(nil),       // 10: sub2api.plugin.v2.GetInfoResponse
	(*Capability)(nil),            // 11: sub2api.plugin.v2.Capability
	(*HealthRequest)(nil),         // 12: sub2api.plugin.v2.HealthRequest
	(*HealthResponse)(nil),        // 13: sub2api.plugin.v2.HealthResponse
	(*ConfigRequest)(nil),         // 14: sub2api.plugin.v2.ConfigRequest
	(*ConfigResponse)(nil),        // 15: sub2api.plugin.v2.ConfigResponse
	(*ApplyResponse)(nil),         // 16: sub2api.plugin.v2.ApplyResponse
	(*TestResponse)(nil),          // 17: sub2api.plugin.v2.TestResponse
	(*RequestContext)(nil),        // 18: sub2api.plugin.v2.RequestContext
	(*HeaderValues)(nil),          // 19: sub2api.plugin.v2.HeaderValues
	(*PreprocessRequest)(nil),     // 20: sub2api.plugin.v2.PreprocessRequest
	(*RequestPatch)(nil),          // 21: sub2api.plugin.v2.RequestPatch
	(*PreprocessResponse)(nil),    // 22: sub2api.plugin.v2.PreprocessResponse
	nil,                           // 23: sub2api.plugin.v2.RequestContext.HeadersEntry
	nil,                           // 24: sub2api.plugin.v2.RequestPatch.HeadersEntry
}
var file_extension_proto_depIdxs = []int32{
	11, // 0: sub2api.plugin.v2.GetInfoResponse.capabilities:type_name -> sub2api.plugin.v2.Capability
	23, // 1: sub2api.plugin.v2.RequestContext.headers:type_name -> sub2api.plugin.v2.RequestContext.HeadersEntry
	18, // 2: sub2api.plugin.v2.PreprocessRequest.context:type_name -> sub2api.plugin.v2.RequestContext
	24, // 3: sub2api.plugin.v2.RequestPatch.headers:type_name -> sub2api.plugin.v2.RequestPatch.HeadersEntry
	21, // 4: sub2api.plugin.v2.PreprocessResponse.patch:type_name -> sub2api.plugin.v2.RequestPatch
	19, // 5: sub2api.plugin.v2.RequestContext.HeadersEntry.value:type_name -> sub2api.plugin.v2.HeaderValues
	19, // 6: sub2api.plugin.v2.RequestPatch.HeadersEntry.value:type_name -> sub2api.plugin.v2.HeaderValues
	9,  // 7: sub2api.plugin.v2.ExtensionPlugin.GetInfo:input_type -> sub2api.plugin.v2.GetInfoRequest
	12, // 8: sub2api.plugin.v2.ExtensionPlugin.Health:input_type -> sub2api.plugin.v2.HealthRequest
	14, // 9: sub2api.plugin.v2.ExtensionPlugin.ValidateConfig:input_type -> sub2api.plugin.v2.ConfigRequest
	14, // 10: sub2api.plugin.v2.ExtensionPlugin.ApplyConfig:input_type -> sub2api.plugin.v2.ConfigRequest
	14, // 11: sub2api.plugin.v2.ExtensionPlugin.TestConfig:input_type -> sub2api.plugin.v2.ConfigRequest
	20, // 12: sub2api.plugin.v2.ExtensionPlugin.Preprocess:input_type -> sub2api.plugin.v2.PreprocessRequest
	0,  // 13: sub2api.plugin.v2.ExtensionPlugin.AttachHost:input_type -> sub2api.plugin.v2.AttachHostRequest
	2,  // 14: sub2api.plugin.v2.HostServices.Log:input_type -> sub2api.plugin.v2.HostLogRequest
	3,  // 15: sub2api.plugin.v2.HostServices.Metric:input_type -> sub2api.plugin.v2.HostMetricRequest
	1,  // 16: sub2api.plugin.v2.HostServices.ReadConfig:input_type -> sub2api.plugin.v2.HostCapabilityRequest
	5,  // 17: sub2api.plugin.v2.HostServices.ReadSecret:input_type -> sub2api.plugin.v2.HostSecretRequest
	7,  // 18: sub2api.plugin.v2.HostServices.PublishEvent:input_type -> sub2api.plugin.v2.HostEventRequest
	10, // 19: sub2api.plugin.v2.ExtensionPlugin.GetInfo:output_type -> sub2api.plugin.v2.GetInfoResponse
	13, // 20: sub2api.plugin.v2.ExtensionPlugin.Health:output_type -> sub2api.plugin.v2.HealthResponse
	15, // 21: sub2api.plugin.v2.ExtensionPlugin.ValidateConfig:output_type -> sub2api.plugin.v2.ConfigResponse
	16, // 22: sub2api.plugin.v2.ExtensionPlugin.ApplyConfig:output_type -> sub2api.plugin.v2.ApplyResponse
	17, // 23: sub2api.plugin.v2.ExtensionPlugin.TestConfig:output_type -> sub2api.plugin.v2.TestResponse
	22, // 24: sub2api.plugin.v2.ExtensionPlugin.Preprocess:output_type -> sub2api.plugin.v2.PreprocessResponse
	16, // 25: sub2api.plugin.v2.ExtensionPlugin.AttachHost:output_type -> sub2api.plugin.v2.ApplyResponse
	8,  // 26: sub2api.plugin.v2.HostServices.Log:output_type -> sub2api.plugin.v2.HostAck
	8,  // 27: sub2api.plugin.v2.HostServices.Metric:output_type -> sub2api.plugin.v2.HostAck
	4,  // 28: sub2api.plugin.v2.HostServices.ReadConfig:output_type -> sub2api.plugin.v2.HostConfigResponse
	6,  // 29: sub2api.plugin.v2.HostServices.ReadSecret:output_type -> sub2api.plugin.v2.HostSecretResponse
	8,  // 30: sub2api.plugin.v2.HostServices.PublishEvent:output_type -> sub2api.plugin.v2.HostAck
	19, // [19:31] is the sub-list for method output_type
	7,  // [7:19] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_extension_proto_init() }
func file_extension_proto_init() {
	if File_extension_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_extension_proto_rawDesc), len(file_extension_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_extension_proto_goTypes,
		DependencyIndexes: file_extension_proto_depIdxs,
		MessageInfos:      file_extension_proto_msgTypes,
	}.Build()
	File_extension_proto = out.File
	file_extension_proto_goTypes = nil
	file_extension_proto_depIdxs = nil
}
