// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: transport.proto

package wire

import (
	v1 "github.com/Wei-Shaw/sub2api/pkg/pluginapi/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_transport_proto protoreflect.FileDescriptor

const file_transport_proto_rawDesc = "" +
	"\n" +
	"\x0ftransport.proto\x12\x11sub2api.plugin.v2\x1a\fplugin.proto2k\n" +
	"\x13ProtectionTransport\x12T\n" +
	"\aForward\x12!.sub2api.plugin.v1.ForwardRequest\x1a\".sub2api.plugin.v1.ForwardResponse(\x010\x01B8Z6github.com/Wei-Shaw/sub2api/pkg/pluginapi/v2/wire;wireb\x06proto3"

var file_transport_proto_goTypes = []any{
	(*v1.ForwardRequest)(nil),  // 0: sub2api.plugin.v1.ForwardRequest
	(*v1.ForwardResponse)(nil), // 1: sub2api.plugin.v1.ForwardResponse
}
var file_transport_proto_depIdxs = []int32{
	0, // 0: sub2api.plugin.v2.ProtectionTransport.Forward:input_type -> sub2api.plugin.v1.ForwardRequest
	1, // 1: sub2api.plugin.v2.ProtectionTransport.Forward:output_type -> sub2api.plugin.v1.ForwardResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transport_proto_init() }
func file_transport_proto_init() {
	if File_transport_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transport_proto_rawDesc), len(file_transport_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transport_proto_goTypes,
		DependencyIndexes: file_transport_proto_depIdxs,
	}.Build()
	File_transport_proto = out.File
	file_transport_proto_goTypes = nil
	file_transport_proto_depIdxs = nil
}
