// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.3
// source: transport.proto

package wire

import (
	context "context"
	v1 "github.com/Wei-Shaw/sub2api/pkg/pluginapi/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProtectionTransport_Forward_FullMethodName = "/sub2api.plugin.v2.ProtectionTransport/Forward"
)

// ProtectionTransportClient is the client API for ProtectionTransport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Optional service, authorized by openai.oauth.protection_transport.v1.
// Reuses the established streaming framing without changing legacy dispatch.
type ProtectionTransportClient interface {
	Forward(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[v1.ForwardRequest, v1.ForwardResponse], error)
}

type protectionTransportClient struct {
	cc grpc.ClientConnInterface
}

func NewProtectionTransportClient(cc grpc.ClientConnInterface) ProtectionTransportClient {
	return &protectionTransportClient{cc}
}

func (c *protectionTransportClient) Forward(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[v1.ForwardRequest, v1.ForwardResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProtectionTransport_ServiceDesc.Streams[0], ProtectionTransport_Forward_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[v1.ForwardRequest, v1.ForwardResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProtectionTransport_ForwardClient = grpc.BidiStreamingClient[v1.ForwardRequest, v1.ForwardResponse]

// ProtectionTransportServer is the server API for ProtectionTransport service.
// All implementations must embed UnimplementedProtectionTransportServer
// for forward compatibility.
//
// Optional service, authorized by openai.oauth.protection_transport.v1.
// Reuses the established streaming framing without changing legacy dispatch.
type ProtectionTransportServer interface {
	Forward(grpc.BidiStreamingServer[v1.ForwardRequest, v1.ForwardResponse]) error
	mustEmbedUnimplementedProtectionTransportServer()
}

// UnimplementedProtectionTransportServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProtectionTransportServer struct{}

func (UnimplementedProtectionTransportServer) Forward(grpc.BidiStreamingServer[v1.ForwardRequest, v1.ForwardResponse]) error {
	return status.Error(codes.Unimplemented, "method Forward not implemented")
}
func (UnimplementedProtectionTransportServer) mustEmbedUnimplementedProtectionTransportServer() {}
func (UnimplementedProtectionTransportServer) testEmbeddedByValue()                             {}

// UnsafeProtectionTransportServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProtectionTransportServer will
// result in compilation errors.
type UnsafeProtectionTransportServer interface {
	mustEmbedUnimplementedProtectionTransportServer()
}

func RegisterProtectionTransportServer(s grpc.ServiceRegistrar, srv ProtectionTransportServer) {
	// If the following call panics, it indicates UnimplementedProtectionTransportServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProtectionTransport_ServiceDesc, srv)
}

func _ProtectionTransport_Forward_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProtectionTransportServer).Forward(&grpc.GenericServerStream[v1.ForwardRequest, v1.ForwardResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProtectionTransport_ForwardServer = grpc.BidiStreamingServer[v1.ForwardRequest, v1.ForwardResponse]

// ProtectionTransport_ServiceDesc is the grpc.ServiceDesc for ProtectionTransport service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProtectionTransport_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sub2api.plugin.v2.ProtectionTransport",
	HandlerType: (*ProtectionTransportServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Forward",
			Handler:       _ProtectionTransport_Forward_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "transport.proto",
}
